hash -d cellar=/usr/local/Cellar
hash -d cask=/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks
hash -d vers=/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions/Casks

export SAXON=/usr/local/bin/saxon

export GOPATH=/Users/sven/go
export GOBIN=$GOPATH/bin

export MONO_GAC_PREFIX=/usr/local

PERL5LIB="/Users/sven/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/Users/sven/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/Users/sven/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/sven/perl5"; export PERL_MM_OPT;

typeset -U path
path=(
    ~/bin
    $GOBIN
    ~/.composer/vendor/bin
    ~/.local/bin
    ~/perl5/bin
    /Library/TeX/texbin
    /usr/local/bin
    /usr/local/sbin
    /usr/bin
    /usr/sbin
    /bin
    /sbin
)

typeset -U cdpath
cdpath=(
    .
    ~/src
    ~/swk
    ~/Documents/Work/
    ~/dotfiles/
    $cdpath
)

typeset -U fpath
fpath=(
    /usr/local/share/zsh/zsh-completions
    /usr/local/share/zsh/functions
    $fpath
)

# eval "$(hub alias -s)"
eval "$(pyenv init -)"
eval "$(pipenv --completion)"
