hash -d cellar=/usr/local/Cellar
hash -d cask=/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks
hash -d vers=/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions/Casks

export SAXON=/usr/local/bin/saxon

export GOPATH=/Users/sven/go
export GOBIN=$GOPATH/bin

export LDFLAGS="-L/usr/local/opt/bison/lib"

export OPENSSL_ROOT_DIR=/usr/local/opt/openssl

typeset -U path
path=(
    ~/bin
    $GOBIN
    /usr/local/opt/awscli@1/bin
    ~/.composer/vendor/bin
    ~/.local/bin
    /Library/TeX/texbin
    /usr/local/bin
    /usr/local/sbin
    /usr/bin
    /usr/sbin
    /bin
    /sbin
)

typeset -U fpath
fpath=(
    /usr/local/share/zsh/zsh-completions
    /usr/local/share/zsh/functions
    $fpath
)

# eval "$(hub alias -s)"
# eval "$(pipenv --completion)"
