hash -d cellar=/usr/local/Cellar
hash -d cask=/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks
hash -d vers=/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions/Casks

export SAXON=/usr/local/bin/saxon

export GOPATH=/Users/sven/go
export GOBIN=$GOPATH/bin

export MONO_GAC_PREFIX=/usr/local

typeset -U path
path=(
    ~/bin
    $GOBIN
    ~/.composer/vendor/bin
    ~/.local/bin
    /Library/TeX/texbin
    /usr/local/bin
    /usr/local/sbin
    /usr/bin
    /usr/sbin
    /bin
    /sbin
)

typeset -U cdpath
cdpath=(
    .
    ~/src
    ~/swk
    ~/Documents/Work/
    ~/dotfiles/
    $cdpath
)

typeset -U fpath
fpath=(
    /usr/local/share/zsh/zsh-completions
    /usr/local/share/zsh/functions
    $fpath
)

# eval "$(hub alias -s)"
eval "$(pyenv init -)"
eval "$(pipenv --completion)"
