. $HOME/.bashrc

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi
if [ -f /Source/PHP/phake/phake_completion.sh ]; then
  . /Source/PHP/phake/phake_completion.sh
fi
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

export PATH="$HOME/.cargo/bin:$PATH"
